// /AvisoPrivacidad.tsx
export default function AvisoPrivacidad() {
  return (
        <div>
            <h2 className="relative text-[2rem] mt-10 mb-4 font-nissanBold before:content-[''] before:absolute before:top-[0px] before:left-0 before:w-[50px] before:h-[4px] before:bg-[var(--vardi-color)]">
                <b>AVISO DE PRIVACIDAD</b>
            </h2>
            <p>El presente Aviso de Privacidad (en adelante el “Aviso”) establece los términos y condiciones en virtud de los cuales las compañías Distribuidora Nissan S.A. Calle 13 No. 50-69 <a href="https://www.dinissan.com.co/" target='_blank' className="underline underline-offset-2 decoration-black">www.dinissan.com.co</a> Tel 018000423854 con domicilio en Bogotá (1) 4866870 Talleres Autorizados S.A. Calle 13 No. 50-83 <a href="https://www.dinissan.com.co/" target='_blank' className="underline underline-offset-2 decoration-black">www.dinissan.com.co</a> Tel 018000423854 con domicilio en Bogotá (1) 4866870, Vardí Agencia de Seguros Ltda Av 19 No. 114-65 Of 502 <a href="https://www.vardiseguros.com.co/" target='_blank' className="underline underline-offset-2 decoration-black">www.vardiseguros.com.co</a> Tel 018000423891 con domicilio en Bogotá (1) 5086070, COM Automotriz S.A. Av Calle 127 No. 70G - 59/63 <a href="https://www.vardiautosusados.com.co/" target='_blank' className="underline underline-offset-2 decoration-black">www.vardiautosusados.com.co</a> – <a href="https://www.changan.com.co/" target='_blank' className="underline underline-offset-2 decoration-black">www.changan.com.co</a> Tel 018000423818 Bogotá (1) 4866872, Vardí Inversiones S.A. Calle 13 No. 50- 69 en la ciudad de Bogotá <a href="https://www.dinissan.com.co/" target='_blank' className="underline underline-offset-2 decoration-black">www.dinissan.com.co</a> Tel 018000423891 con domicilio en Bogotá (1) 4866871, Mellvar S.A.S. Calle 98 No. 70 – 92 piso 12, Nissan Mexicana, S.A. de C.V. (NMEX). Av. Insurgentes Sur 1958, Colonia Florida C.P. 01030, con domicilio en México D.F. <a href="https://www.nissan.com.mx/" target='_blank' className="underline underline-offset-2 decoration-black">www.nissan.com.mx</a> Tel 01 8000 647726, realizarán el tratamiento de sus datos personales.</p>

             <h2 className="relative text-[2rem] mt-10 mb-4 font-nissanBold before:content-[''] before:absolute before:top-[0px] before:left-0 before:w-[50px] before:h-[4px] before:bg-[var(--vardi-color)]">
                <b>TRATAMIENTO Y FINALIDAD</b>
            </h2>
             <p>El tratamiento, recolección, almacenamiento, uso, circulación que realizarán las compañías responsables con su información personal será el siguiente: (i) Efectuar las gestiones pertinentes para el desarrollo del objeto social de cada una de las compañías responsables, en lo referente al cumplimiento del objeto del contrato celebrado con el Titular de la información; (ii) Realizar evaluaciones de servicio, investigaciones de mercado; enviar información sobre eventos, concursos y rifas; enviar comunicaciones publicitarias, comerciales y promocionales de sus productos y servicios, información relacionada con productos para la financiación en la adquisición de sus bienes y servicios, realizar encuestas, y dar a conocer noticias relacionadas con los productos y servicios de dichas empresas. (iii) Gestionar trámites relacionados con las solicitudes, quejas y reclamos, efectuar encuestas de satisfacción respecto de los bienes y servicios ofrecidos ya sea directamente por el Responsable o por el Encargado de la Información; (iv)Transmitir los datos personales fuera del país a terceros con los cuales la Compañía Responsable haya suscrito un contrato de procesamiento de datos y sea necesario entregárselo para el cumplimiento del objeto contractual; (v) Para la prestación de servicio posventa y atención de los siniestros; (vi) Control y prevención del fraude; (vii) Adelantar procedimientos de seguridad en las instalaciones de las Compañías Responsables y/o como medio probatorio ante una autoridad judicial o administrativa, cuando los datos sean obtenidos a través de grabaciones o suministrados por el Titular a la empresa de vigilancia para el ingreso o permanencia en las instalaciones de las Compañías Responsables; (viii) Fines estadísticos, de consulta, gremiales y actuariales.</p>

             <h2 className="relative text-[2rem] mt-10 mb-4 font-nissanBold before:content-[''] before:absolute before:top-[0px] before:left-0 before:w-[50px] before:h-[4px] before:bg-[var(--vardi-color)]"><b>DERECHOS DE TITULAR</b></h2>
             <p>Como titular de sus datos personales Usted tiene derecho a:</p>
             <ul className="list-disc pl-6">
              <li>(I) Acceder de forma gratuita a los datos proporcionados que hayan sido objeto de tratamiento.</li>
              <li>(II) Conocer, actualizar y rectificar su información frente a datos parciales, inexactos, incompletos, fraccionados, que induzcan a error, o aquellos cuyo tratamiento estéprohibido o no haya sido autorizado.</li>
              <li>(III) Solicitar prueba de la autorización otorgada.</li>
              <li>(IV) Presentar ante la Superintendencia de Industria y Comercio (SIC) quejas por infracciones a lo dispuesto en la normatividad vigente.</li>
              <li>(V) Revocar la autorización y/o solicitar la supresión del dato, siempre que no exista un deber legal o contractual que impida eliminarlos.</li>
              <li>(VI) Abstenerse de responder las preguntas sobre datos sensibles. Tendrán carácter facultativo las respuestas que versen sobre datos sensibles o sobre datos de las niñas y niños y adolescentes.</li>
             </ul>

             <h2 className="relative text-[2rem] mt-10 mb-4 font-nissanBold before:content-[''] before:absolute before:top-[0px] before:left-0 before:w-[50px] before:h-[4px] before:bg-[var(--vardi-color)]"><b>MECANISMOS PARA CONOCER LA POLÍTICA DE TRATAMIENTO</b></h2>
             <p>El titular puede acceder a la Política de Tratamiento de información, la cual se encuentra publicada para Distribuidora Nissan S.A., Talleres Autorizados S.A., Com Automotriz S.A., y/o Vardí Inversiones S.A. en la página web <a href="https://www.dinissan.com.co/contacto/" target='_blank' className="underline underline-offset-2 decoration-black">www.dinissan.com.co/contactenos</a>, para Vardí Agencia de Seguros Ltda en la página web <a href="https://www.vardiseguros.com.co" target='_blank' className="underline underline-offset-2 decoration-black">www.vardiseguros.com.co</a>, Mellvar S.A.S. Calle 98 No. 70 – 92 piso 12, En relación con Nissan Mexicana, S.A. de C.V. (NMEX), dichas políticas podrán ser consultadas en la página web <a href="https://www.nissan.com.mx" target='_blank' className="underline underline-offset-2 decoration-black">www.nissan.com.mx</a>, enlace LEGALES.</p>
         </div>
    );    
}