services:
  vardi-form:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
    container_name: vardi-form
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped
